version: "3"

services:
    mysql:
        container_name: mysql
        image: mysql:8.0
        restart: always
        volumes:
            - ${USER_PATH}/mysql:/var/lib/mysql
            - ./mysql/my.cnf:/etc/my.cnf
        environment:
            MYSQL_ROOT_PASSWORD: ${PASSWORD}
            TZ: Asia/Seoul
        ports:
            - ${MYSQL_PORT}:3306
    redis:
        container_name: redis
        image: redis
        restart: always
        volumes:
            - ${DATA_PATH}/redis:/data
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        ports:
            - ${REDIS_PORT}:6379
        command: 
            redis-server /usr/local/etc/redis/redis.conf
    npm:
        container_name: npm
        image: 'jc21/nginx-proxy-manager:latest'
        restart: unless-stopped
        ports:
            - '80:80'
            - '81:81'
            - '443:443'
        environment:
            TZ: Asia/Seoul
            DB_MYSQL_HOST: "npm_db"
            DB_MYSQL_PORT: 3306
            DB_MYSQL_USER: "npm"
            DB_MYSQL_PASSWORD: "npm"
            DB_MYSQL_NAME: "npm"
        volumes:
            - ${DATA_PATH}/npm:/data
            - /data/letsencrypt:/etc/letsencrypt
            - ./npm/http_top.conf:/data/nginx/custom/http_top.conf
            - ./npm/events.conf:/data/nginx/custom/events.conf
        depends_on:
            - npm_db
    npm_db:
        container_name: npm_db
        image: 'jc21/mariadb-aria:latest'
        restart: unless-stopped
        environment:
            TZ: Asia/Seoul
            MYSQL_ROOT_PASSWORD: 'npm'
            MYSQL_DATABASE: 'npm'
            MYSQL_USER: 'npm'
            MYSQL_PASSWORD: 'npm'
        volumes:
            - ${DATA_PATH}/npm_db:/var/lib/mysql
    portainer:
        container_name: portainer
        image: 'portainer/portainer-ce:latest'
        restart: always
        ports:
            - '8000:8000'
            - '{PORTAINER_PORT}:9000'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${DATA_PATH}/portainer:/data